config/routes.rb
Rails.application.routes.draw do
 
  get 'customers/index'

  root 'homepage#index'

  resources :pettypes
  resources :pets
  resources :doctors
  resources :appointments
  

end

app/controllers/pettypes_controller.rb
class PettypesController < ApplicationController
  before_action :set_pettype, only: [:show, :edit, :update, :destroy]

  # GET /pettypes
  # GET /pettypes.json
  def index
    @pettypes = Pettype.all
  end

  # GET /pettypes/1
  # GET /pettypes/1.json
  def show
  end

  # GET /pettypes/new
  def new
    @pettype = Pettype.new
  end

  # GET /pettypes/1/edit
  def edit
  end

  # POST /pettypes
  # POST /pettypes.json
  def create
    @pettype = Pettype.new(pettype_params)

    respond_to do |format|
      if @pettype.save
        format.html { redirect_to @pettype, notice: 'Pettype was successfully created.' }
        format.json { render :show, status: :created, location: @pettype }
      else
        format.html { render :new }
        format.json { render json: @pettype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pettypes/1
  # PATCH/PUT /pettypes/1.json
  def update
    respond_to do |format|
      if @pettype.update(pettype_params)
        format.html { redirect_to @pettype, notice: 'Pettype was successfully updated.' }
        format.json { render :show, status: :ok, location: @pettype }
      else
        format.html { render :edit }
        format.json { render json: @pettype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pettypes/1
  # DELETE /pettypes/1.json
  def destroy
    @pettype.destroy
    respond_to do |format|
      format.html { redirect_to pettypes_url, notice: 'Pettype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pettype
      @pettype = Pettype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pettype_params
      params.require(:pettype).permit(:name)
    end
end

app/helpers/pettypes_helper.rb
module PettypesHelper
end

app/views/pettypes/_form.html.erb
<%= form_for(@pettype) do |f| %>
  <% if @pettype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pettype.errors.count, "error") %> prohibited this pettype from being saved:</h2>

      <ul>
      <% @pettype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pettypes/edit.html.erb
<h1>Editing Pettype</h1>

<%= render 'form' %>

<%= link_to 'Show', @pettype %> |
<%= link_to 'Back', pettypes_path %>

app/views/pettypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pettypes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pettypes.each do |pettype| %>
      <tr>
        <td><%= pettype.name %></td>
        <td><%= link_to 'Show', pettype %></td>
        <td><%= link_to 'Edit', edit_pettype_path(pettype) %></td>
        <td><%= link_to 'Destroy', pettype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pettype', new_pettype_path %>

app/views/pettypes/new.html.erb
<h1>New Pettype</h1>

<%= render 'form' %>

<%= link_to 'Back', pettypes_path %>

app/views/pettypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pettype.name %>
</p>

<%= link_to 'Edit', edit_pettype_path(@pettype) %> |
<%= link_to 'Back', pettypes_path %>