config/routes.rb
Rails.application.routes.draw do
 
  get 'customers/index'

  root 'homepage#index'

  resources :pettypes
  resources :pets
  resources :doctors
  resources :appointments
  

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  has_one :pettype, primary_key: "pettype_id", foreign_key: "id"
  has_many :appointments, primary_key: "appointment_id", foreign_key: "id"

  validates :name, presence: true
  validates :breed, presence: true
  validates :age, presence: true
  validates :weight, presence: true
  validates :lastvisit, presence: true
end

app/models/pettype.rb
class Pettype < ActiveRecord::Base
  belongs_to :pet
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :breed, :age, :weight, :lastvisit, :pettype_id)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_for(@pet,:html => { :class =>"form-horizontal" }) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="panel panel-primary">
      <div class="panel-heading"><h3>Pet Details</h3></div>
      <div class="panel-body">

        <div class="form-group">
          <%= f.label :name, "Pet Name", class: 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%=f.text_field :name,  :placeholder => "Pet Name", class: 'form-control', :maxlength=> 35 %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :pettype_id, "Pet Type:", class: 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%=f.collection_select :pettype_id,  Pettype.order(:name),:id, :name, {}, class: 'form-control' %>
            <%#= f.select :pettype, [['Dog','dog'],['Cat','cat'],['Bird','bird']] %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :breed, "Breed:", class: 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%=f.text_field :breed,  :placeholder => "Breed", class: 'form-control', :maxlength=> 35 %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :age, "Age:", class: 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%=f.text_field :age,  :placeholder => "Age", class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :weight, "Weight:", class: 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%=f.text_field :weight,  :placeholder => "Weight", class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :lastvisit, "Date of Last Visit:", class: 'control-label col-sm-2' %>
          <div class="col-sm-4">
            <%=f.date_select :lastvisit,  class: 'form-control' %>
          </div>
        </div>





      </div>



    </div>
    <div style="text-align: center;margin-left: auto;margin-right: auto">

    <%= f.submit "Submit", :class=> 'btn btn-primary' %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %><br>
<div style="text-align: center;margin-left: auto;margin-right: auto">
<%= link_to 'Show', @pet, :class=> 'btn btn-primary' %>
<%= link_to 'Back', pets_path, :class=> 'btn btn-primary' %>
</div>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-primary">
  <div class="panel-heading"><h3>Pet Records Listing</h3></div>
  <div class="panel-body">
    <table class="table table-striped table-bordered" cellspacing="0" width="100%">
      <thead>
      <tr>

        <th colspan="3">Pet Name</th>
        <th colspan="3">Pet Type</th>
        <th colspan="3">Breed</th>
        <th colspan="3">Age</th>
        <th colspan="3">Weight</th>
        <th colspan="3">Date of Last Visit</th>
        <th colspan="3" style="text-align: center;">View</th>
        <th colspan="3" style="text-align: center;">Edit</th>
        <th colspan="3" style="text-align: center;">Delete</th>

      </tr>
      </thead>

      <tbody>
      <% @pets.each do |p| %>
          <tr>
            <td colspan="3"><%=p.name %></td>
            <td colspan="3"><%=p.pettype.name %></td>
            <td colspan="3"><%=p.breed %></td>
            <td colspan="3"><%=p.age %></td>
            <td colspan="3"><%=p.weight %></td>
            <td colspan="3"><%=p.lastvisit.to_s(:long) %></td>
            <td colspan="3" style="text-align: center;"><%= link_to p do %>
                                                         <span class="glyphicon glyphicon-search"></span>
                                                        <% end %></td>
            <td colspan="3" style="text-align: center;"><%= link_to edit_pet_path(p.id) do %> <span class="glyphicon glyphicon-pencil"></span>
              <% end %></td>
            <td colspan="3" style="text-align: center;"><%= link_to  p, method: :delete, data: { confirm: 'Are you sure?' } do %> <span class="glyphicon glyphicon-trash"></span>
              <% end %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

  </div>
</div>
<br>

<div style="text-align: center;margin-left: auto;margin-right: auto">
  <%= link_to 'New Pet Record', new_pet_path,  :class=> 'btn btn-primary' %>
</div>

app/views/pets/new.html.erb
<h1>New Pet Record</h1>

<%= render 'form' %><br>
<div style="text-align: center;margin-left: auto;margin-right: auto">
<%= link_to 'Back', pets_path, :class => 'btn btn-primary' %>
</div>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
  <div class="panel-heading"><h3>Pet Details</h3></div>
  <div class="panel-body">
    <table class="table table-striped table-bordered" cellspacing="0" width="50%">

      <tbody>

      <tr><td><strong>Pet Name:</strong> </td><td><%= @pet.name %></td></tr>
      <tr><td><strong>Pet Type:</strong> </td><td><%= @pet.pettype %></td></tr>
      <tr><td><strong>Breed:</strong> </td><td><%= @pet.breed %></td></tr>
      <tr><td><strong>Age:</strong> </td><td><%= @pet.age %></td></tr>
      <tr><td><strong>Weight:</strong> </td><td><%= @pet.weight %></td></tr>
      <tr><td><strong>Last Visit:</strong> </td><td><%=  @pet.lastvisit.to_s(:long) %></td></tr>
      </tbody>

    </table>

  </div>
</div>

<div style="text-align: center;margin-left: auto;margin-right: auto">

  <%= link_to 'Edit', edit_pet_path(@pet), :class=> 'btn btn-primary' %>
  <%= link_to 'Back', pets_path, :class=> 'btn btn-primary' %>
</div>