config/routes.rb
Rails.application.routes.draw do
 
  get 'customers/index'

  root 'homepage#index'

  resources :pettypes
  resources :pets
  resources :doctors
  resources :appointments
  

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_many :appointments
  validates :name, presence: true, length: {maximum: 35}
  validates_length_of :zip, :maximum => 5
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name, :address, :city, :state, :zip, :school, :years)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor,:html => { :class =>"form-horizontal" }) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


        <div class="panel panel-primary">
          <div class="panel-heading"><h3>Doctor Details</h3></div>
          <div class="panel-body">

            <div class="form-group">
                  <%= f.label :name, "Doctor's Name:", class: 'control-label col-sm-2' %>
                  <div class="col-sm-4">
                    <%=f.text_field :name,  :placeholder => "Doctor's Name", class: 'form-control', :maxlength=> 35 %>
                  </div>
            </div>


            <div class="form-group">
              <%= f.label :name, "Address:", class: 'control-label col-sm-2' %>
              <div class="col-sm-4">
                <%=f.text_field :address,  :placeholder => "Address", class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :city, "City:", class: 'control-label col-sm-2' %>
              <div class="col-sm-4">
                <%=f.text_field :city,  :placeholder => "City", class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :state, "State:", class: 'control-label col-sm-2' %>
              <div class="col-sm-4">
                <%=f.text_field :state,  :placeholder => "State", class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :zip, "Zip:", class: 'control-label col-sm-2' %>
              <div class="col-sm-4">
                <%=f.text_field :zip,  :placeholder => "Zip", class: 'form-control', :maxlength=> 5 %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :school, "School Received Degree From:", class: 'control-label col-sm-2' %>
              <div class="col-sm-4">
                <%=f.text_field :school,  :placeholder => "School Received Degree From", class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :years, "Years in Practice:", class: 'control-label col-sm-2' %>
              <div class="col-sm-4">
                <%=f.number_field :years,   in: 1...101,  :placeholder => "Years in Practice", class: 'form-control' %>
              </div>
            </div>





          </div>



        </div>

      <div style="text-align: center;margin-left: auto;margin-right: auto">
        <%= f.submit "Submit", :class=> 'btn btn-primary' %>
      </div>
<% end %>

app/views/doctors/edit.html.erb
h1>Editing Doctor</h1>

<%= render 'form' %>

<br>
  <div style="text-align: center;margin-left: auto;margin-right: auto">

    <%= link_to 'Show', @doctor, class: 'btn btn-primary'  %>
    <%= link_to 'Back', doctors_path , class: 'btn btn-primary' %>
  </div>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>


<div class="panel panel-primary">
  <div class="panel-heading"><h3>Doctor Listing</h3></div>
  <div class="panel-body">
<table class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th colspan="3">Name</th>
      <th colspan="3">Address</th>
      <th colspan="3">City</th>
      <th colspan="3">State</th>
      <th colspan="3">Zip</th>
      <th colspan="3">Degree From</th>
      <th colspan="3">Years</th>
      <th colspan="3" style="text-align: center;">View</th>
      <th colspan="3" style="text-align: center;">Edit</th>
      <th colspan="3" style="text-align: center;">Delete</th>

    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |d| %>
      <tr>
        <td colspan="3"><%=d.name %></td>
        <td colspan="3"><%=d.address %></td>
        <td colspan="3"><%=d.city %></td>
        <td colspan="3"><%=d.state %></td>
        <td colspan="3"><%=d.zip %></td>
        <td colspan="3"><%=d.school %></td>
        <td colspan="3"><%=d.years %></td>
        <td colspan="3" style="text-align: center;"><%= link_to d do %>
              <span class="glyphicon glyphicon-search"></span>
          <% end %></td>
        <td colspan="3" style="text-align: center;"><%= link_to edit_doctor_path(d.id) do %> <span class="glyphicon glyphicon-pencil"></span>
          <% end %></td>
        <td colspan="3" style="text-align: center;"><%= link_to  d, method: :delete, data: { confirm: 'Are you sure?' } do %> <span class="glyphicon glyphicon-trash"></span>
          <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div></div>

  <div style="text-align: center;margin-left: auto;margin-right: auto">
<%= link_to 'New Doctor', new_doctor_path, class: 'btn btn-primary' %>
</div></div>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>
<div class="container">
<%= render 'form' %>
<br>
<div style="text-align: center;margin-left: auto;margin-right: auto">
<%= link_to 'Back', doctors_path,  :class=> 'btn btn-primary' %>

</div>

</div>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="panel panel-primary">
    <div class="panel-heading"><h3><%= @doctor.name + "'s" %> Details</h3></div>
    <div class="panel-body">
      <table class="table table-striped table-bordered" cellspacing="0" width="50%">

        <tbody>

        <tr><td><strong>Doctor's Name:</strong> </td><td><%= @doctor.name %></td></tr>
        <tr><td><strong>Doctor's Address:</strong> </td><td><%= @doctor.address %></td></tr>
        <tr><td><strong>Doctor's City:</strong> </td><td><%= @doctor.city %></td></tr>
        <tr><td><strong>Doctor's State:</strong> </td><td><%= @doctor.state %></td></tr>
        <tr><td><strong>Doctor's Zip:</strong> </td><td><%= @doctor.zip %></td></tr>
        <tr><td><strong>School Received Degree From:</strong> </td><td><%= @doctor.school %></td></tr>
        <tr><td><strong>Years in Practice:</strong> </td><td><%= @doctor.years %></td></tr>
      </tbody>
      </table>

      </div>
    </div>


    <div style="text-align: center;margin-left: auto;margin-right: auto">
<%= link_to 'Edit', edit_doctor_path(@doctor), :class=> 'btn btn-primary' %>
<%= link_to 'Back', doctors_path, :class=> 'btn btn-primary' %>
</div>
    </div>